array_width                  = 60
attr_fn_like_width           = 70
binop_separator              = "Back"
blank_lines_lower_bound      = 0
blank_lines_upper_bound      = 1
brace_style                  = "SameLineWhere"
chain_width                  = 100
color                        = "Auto"
combine_control_expr         = true
comment_width                = 95
condense_wildcard_suffixes   = false
control_brace_style          = "AlwaysSameLine"
disable_all_formatting       = false
doc_comment_code_block_width = 100
edition                      = "2021"
empty_item_single_line       = true
enum_discrim_align_threshold = 0
error_on_line_overflow       = false
error_on_unformatted         = false
fn_args_layout               = "Tall"
fn_call_width                = 60
fn_single_line               = true
force_explicit_abi           = true
force_multiline_blocks       = false
format_code_in_doc_comments  = true
format_generated_files       = true
format_macro_bodies          = true
format_macro_matchers        = false
format_strings               = true
hard_tabs                    = false
hex_literal_case             = "Preserve"
hide_parse_errors            = false
ignore                       = []
imports_granularity          = "Crate"
imports_indent               = "Block"
imports_layout               = "Mixed"
indent_style                 = "Block"
inline_attribute_width       = 0
match_arm_blocks             = true
match_arm_leading_pipes      = "Never"
match_block_trailing_comma   = true
max_width                    = 110
merge_derives                = true
#merge_imports                   = "Deprecated"
group_imports            = "StdExternalCrate"
newline_style            = "Auto"
normalize_comments       = true
normalize_doc_attributes = true
overflow_delimited_expr  = true
remove_nested_parens     = true
reorder_impl_items       = true
reorder_imports          = true
reorder_modules          = true
#required_version                = CARGO_PKG_VERSION
single_line_if_else_max_width = 100
skip_children                 = false
space_after_colon             = true
space_before_colon            = false
spaces_around_ranges          = false
struct_field_align_threshold  = 0
struct_lit_single_line        = true
struct_lit_width              = 18
struct_variant_width          = 35
tab_spaces                    = 4
trailing_comma                = "Vertical"
trailing_semicolon            = true
type_punctuation_density      = "Wide"
unstable_features             = true
use_field_init_shorthand      = true
use_small_heuristics          = "Max"
use_try_shorthand             = true
version                       = "One"
where_single_line             = true
wrap_comments                 = true
