openapi: 3.0.3
info:
  title: Backpack
  description: |-
    Backpack
  version: 1.0.0
servers:
  - url: https://localhost/api/v1
tags:
  - name: app
    description: Everything about apps
    externalDocs:
      description: Find out more
      url: https://github.com/Vrixyz/backpack
paths:
  /apps:
    post:
      tags:
        - app
      summary: Create a new app
      description: Create a new app with given name.
      operationId: createApp
      requestBody:
        description: Create an app
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
        required: true
      responses:
        "201":
          description: Successful operation returns the id of created app.
          content:
            application/json:
              schema:
                description: the id of the created app.
                type: integer
      security:
        - biscuit_token:
            - admin
    get:
      tags:
        - app
      summary: Get apps.
      description: Get all apps the user is admin of.
      operationId: getApp
      responses:
        "200":
          description: Successful operation returns the id of created app.
          content:
            application/json:
              schema:
                description: all apps the user is admin of.
                type: array
                items:
                  $ref: "#/components/schemas/App"
      security:
        - biscuit_token:
            - admin
    delete:
      tags:
        - app
      summary: Delete an existing app
      description: Delete existing app with provided id.
      operationId: deleteApp
      requestBody:
        description: "Deletes an existing app. It should fail if it owns items.\
          Items should be removed or transferred before."
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  description: the id of the app to be deleted
                  type: integer
        required: true
      responses:
        "201":
          description: Successful operation returns the id of created app.
        "401":
          description: Unauthorized. (User is not admin for this app?)
      security:
        - biscuit_token:
            - admin
components:
  schemas:
    App:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 100000
        name:
          type: string
          example: "Game name"
  securitySchemes:
    github_auth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://github.com/login/oauth/access_token
          tokenUrl: todo
          scopes:
            admin: modify managed apps and items definitions
            user: used for modifying user items in low security apps, or authentication forwarded to trusted game server.
    biscuit_token:
      type: http
      scheme: bearer
      bearerFormat: Biscuit
