[package]
name = "example_game_lazy_simple"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11"
bevy_egui = "*"
backpack_client_bevy_egui = { path = "../client_bevy_egui" }
dotenvy = "*"
